// Date: 02/03/2013 19:37:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelFairy extends ModelBase
{
  //fields
    ModelRenderer RightLeg;
    ModelRenderer Body;
    ModelRenderer Head;
    ModelRenderer LeftLeg;
    ModelRenderer LeftArm;
    ModelRenderer RightArm;
    ModelRenderer WingRightTop;
    ModelRenderer WingLeftTop;
    ModelRenderer WingBottomLeft;
    ModelRenderer WingBottomRight;
  
  public ModelFairy()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      RightLeg.mirror = true;
      RightLeg = new ModelRenderer(this, 0, 16);
      RightLeg.addBox(-2F, 0F, -2F, 4, 12, 4);
      RightLeg.setRotationPoint(-2F, 12F, 0F);
      RightLeg.setTextureSize(128, 32);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0F, 0F, 0F);
      RightLeg.mirror = false;
      Body = new ModelRenderer(this, 16, 16);
      Body.addBox(-4F, 0F, -2F, 8, 12, 4);
      Body.setRotationPoint(0F, 0F, 0F);
      Body.setTextureSize(128, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-4F, -8F, -4F, 8, 8, 8);
      Head.setRotationPoint(0F, 0F, 0F);
      Head.setTextureSize(128, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 0, 16);
      LeftLeg.addBox(-2F, 0F, -2F, 4, 12, 4);
      LeftLeg.setRotationPoint(2F, 12F, 0F);
      LeftLeg.setTextureSize(128, 32);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0F, 0F, 0F);
      LeftArm = new ModelRenderer(this, 40, 16);
      LeftArm.addBox(-1F, -2F, -2F, 4, 12, 4);
      LeftArm.setRotationPoint(5F, 2F, 0F);
      LeftArm.setTextureSize(128, 32);
      LeftArm.mirror = true;
      setRotation(LeftArm, 0F, 0F, 0F);
      RightArm.mirror = true;
      RightArm = new ModelRenderer(this, 40, 16);
      RightArm.addBox(-3F, -2F, -2F, 4, 12, 4);
      RightArm.setRotationPoint(-5F, 2F, 0F);
      RightArm.setTextureSize(128, 32);
      RightArm.mirror = true;
      setRotation(RightArm, 0F, 0F, 0F);
      RightArm.mirror = false;
      WingRightTop.mirror = true;
      WingRightTop = new ModelRenderer(this, 64, 0);
      WingRightTop.addBox(-16F, -16F, 0F, 16, 16, 2);
      WingRightTop.setRotationPoint(-2F, 7F, 2F);
      WingRightTop.setTextureSize(128, 32);
      WingRightTop.mirror = true;
      setRotation(WingRightTop, 0F, 0F, 0F);
      WingRightTop.mirror = false;
      WingLeftTop = new ModelRenderer(this, 64, 0);
      WingLeftTop.addBox(0F, -16F, 0F, 16, 16, 2);
      WingLeftTop.setRotationPoint(2F, 7F, 2F);
      WingLeftTop.setTextureSize(128, 32);
      WingLeftTop.mirror = true;
      setRotation(WingLeftTop, 0F, 0F, 0F);
      WingBottomLeft = new ModelRenderer(this, 64, 18);
      WingBottomLeft.addBox(0F, 0F, 0.5F, 12, 12, 1);
      WingBottomLeft.setRotationPoint(2F, 7F, 2F);
      WingBottomLeft.setTextureSize(128, 32);
      WingBottomLeft.mirror = true;
      setRotation(WingBottomLeft, 0F, 0F, 0F);
      WingBottomRight.mirror = true;
      WingBottomRight = new ModelRenderer(this, 64, 18);
      WingBottomRight.addBox(-12F, 0F, 0.5F, 12, 12, 1);
      WingBottomRight.setRotationPoint(-2F, 7F, 2F);
      WingBottomRight.setTextureSize(128, 32);
      WingBottomRight.mirror = true;
      setRotation(WingBottomRight, 0F, 0F, 0F);
      WingBottomRight.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    RightLeg.render(f5);
    Body.render(f5);
    Head.render(f5);
    LeftLeg.render(f5);
    LeftArm.render(f5);
    RightArm.render(f5);
    WingRightTop.render(f5);
    WingLeftTop.render(f5);
    WingBottomLeft.render(f5);
    WingBottomRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
